### ISSUE TITLE
Add group icon customization

### ISSUE THREAD

**Issue by nWidart** [Maatwebsite/Laravel-Sidebar#1]
Would be nice to be able to set a custom group icon.

![screen shot 2015-02-13 at 6 55 22 pm](https://cloud.githubusercontent.com/assets/882397/6192453/5ac8a54a-b3b2-11e4-8837-a6394a40648e.png)

**Comment by patrickbrouwers** [comment]
``` php
$item->toggleIcon = 'fa fa-angle-left'
```

**Comment by nWidart** [comment]
:+1:
