### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by maarten-v** [Maatwebsite/Laravel-Sidebar#20]
It seems important parts of the documentation is missing here:
https://github.com/Maatwebsite/Laravel-Sidebar/wiki/Building-the-Sidebar

How do I add menu's / groups / items ....?

**Comment by patrickbrouwers** [comment]
Indeed never got the change to finish the docs.

The example in the docs does have the example of adding groups and items:

```
$this->menu->group('settings', function(Group $group) {
     $group->item('User Settings');
});
```

For now you can refer to the docs at AsgardCMS:
https://asgardcms.com/docs/core-module/navigation#introduction
