### ISSUE TITLE
Rendering sidebar in View composer

### ISSUE THREAD

**Issue by grafikkaos** [Maatwebsite/Laravel-Sidebar#23]
Quick question for anyone who may have an idea on this..

How do I render the sidebar using the view composer?

I am using teepluss/theme as my theme manager in my laravel projects.  In the config file, the following code allows me to use view composer:

`php`
$theme->partialComposer('sidebar-bar', function($view)
{
    $view->with('sidebar', '');
});

However, I am unsure of how to load the sidebar in the above code?  Anyone have any ideas?

Thanks

**Comment by nWidart** [comment]
Hello,

This is how I do it in AsgardCMS: https://github.com/AsgardCms/Core/blob/master/Composers/SidebarViewCreator.php

**Comment by grafikkaos** [comment]
@nWidart, thanks for the prompt response.  I have implemented something like that in my app.  However when I try to call it within the partial composer view that I am using, it simply will not load.  
`$theme->partialComposer('sidebar-nav', function($view)
            {
                /** @var Illuminate\Contracts\View\View $view */
                 $view->with('sidebar', app\Presenters\SidebarCreator::class);
            });`

When adding {!! $sidebar !!} to my view, I get the "app\Presenters\SidebarCreator" as the output instead of the sidebar itself.

Where could I be going wrong?  I have already made sure that the sidebar class is already registered as well.

**Comment by nWidart** [comment]
I don't know what your theme->partialComposer does. Do you have to use that? It's important to use a view creator and not a view composer in this case, as it needs to run sooner.

**Comment by grafikkaos** [comment]
@nWidart Thanks for the replies.  May have a go at extending the theme package to call the view creator.  Failing that, i will just use a different theme manager for my app to make using the view creator a bit easier

**Comment by grafikkaos** [comment]
@nWidart Managed to extend the theme package that I am using and the sidebar is now showing :)

Quick question however, how do I hide the group heading?  I have noticed in the group.blade.php file, there is a condition if ($group->shouldShowHeading()), where can I set this?

Thanks

**Comment by grafikkaos** [comment]
Actually its probably easier to edit the view file which I have done so its perfect.. Thanks again!
