### ISSUE TITLE
How I can add my own html for sidebar

### ISSUE THREAD

**Issue by giwrgos88** [Maatwebsite/Laravel-Sidebar#26]
Hello, how I can change the default sidebar html with the one that I want?

**Comment by nWidart** [comment]
Hi,

You need to publish the package views and customise those. 

```
php artisan vendor:publish --tag="views"
```

**Comment by giwrgos88** [comment]
I see but is there any other way to do that? I mean tell what view to use? Because in case that I want to use the package inside my own package that means everyone who will use my package will need to go inside your views and change it manually.

**Comment by patrickbrouwers** [comment]
`php artisan vendor:publish --tag="views"` is the only way to do that.
