### ISSUE TITLE
Item append not working properly

### ISSUE THREAD

**Issue by nWidart** [Maatwebsite/Laravel-Sidebar#4]
Situation:

I've got 2 items:

``` php
$item->addItem('posts', function (SidebarItem $item) {
    $item->weight = 0;
    $item->append('admin.blog.post.create');
    $item->route('admin.blog.post.index');
    $item->icon = 'fa fa-copy';
    $item->name = 'Posts';
    $item->authorize(
        $this->auth->hasAccess('blog.posts.index')
    );
});

$item->addItem('categories', function (SidebarItem $item) {
    $item->weight = 1;
    $item->route('admin.blog.category.index');
    $item->icon = 'fa fa-file-text';
    $item->name = 'Categories';
    $item->authorize(
        $this->auth->hasAccess('blog.categories.index')
    );
});
```

The plus gets appended to the `categories` item, not `posts`.

**Comment by nWidart** [comment]
When appending to both items:

![screen shot 2015-02-14 at 3 03 43 pm](https://cloud.githubusercontent.com/assets/882397/6199815/d60e7cb8-b45a-11e4-9dad-fb4707e9e592.png)

**Comment by nWidart** [comment]
Here I've appended to the `page` item, but the plus gets added to the next one:

![screen shot 2015-02-14 at 3 07 08 pm](https://cloud.githubusercontent.com/assets/882397/6199828/3b134b3e-b45b-11e4-91d6-175a66e4344c.png)

**Comment by nWidart** [comment]
Adding a `clearfix` class on the `li` tag would be helpful to be able to float the items left.

**Comment by patrickbrouwers** [comment]
Added the clearfix
