### ISSUE TITLE
LOG.warning: implements the Serializable interface

### ISSUE THREAD

**Issue by wikigods** [Maatwebsite/Laravel-Sidebar#41]
I'm getting LOG.warning: implements the Serializable interface using laravel 9 but I think it's more due to the PHP 8.1.2 version I'm currently using. 

"Warning.
As of PHP 8.1.0, a class that implements Serializable without also implementing __serialize() and __unserialize() will generate a deprecation warning."

My solution is to implement __serialize() and __unserialize() , so as not to have that warning.

![Screenshot_6](https://user-images.githubusercontent.com/71094046/155868811-b1c80fc3-2927-4970-8911-f97a17b08d4a.png)
@patrickbrouwers

**Comment by patrickbrouwers** [comment]
Hey @wikigods, we don't actively support this package anymore. We merge fixes as long as people are still using it and provide the PR themselves. If you want to keep using this package, feel free to provide a PR that fixes the warnings.

**Comment by wikigods** [comment]
Good morning, can you help me with a problem I have when I run the tests (I only need this one test)
for laravel = 9
php = 8.1
phpunit/phpunit = 9.5.10
mockery/mockery = 1.4.4
attached changes I made to the package with commit:
"update implements the Serializable interface".
https://github.com/wikigods/Laravel-Sidebar/commits/master
Sorry for my english

@patrickbrouwers 

![Screenshot_15](https://user-images.githubusercontent.com/71094046/182074218-0716cf5a-e1cb-45e2-b2c5-55b5fa814a3a.png)
![Screenshot_16](https://user-images.githubusercontent.com/71094046/182074216-541e7e45-e34f-4ccc-991d-1cd2b85ee404.png)
