### ISSUE TITLE
Laravel 10 support :)

### ISSUE THREAD

**Issue by Levivb** [Maatwebsite/Laravel-Sidebar#42]
Hey, I noticed the `composer.json` doesn't allow `laravel/framework` 10 as of yet. Is this something you need help with? I reckon it's mainly adding `^10.0` to `laravel/framework` in `composer.json` :)

**Comment by patrickbrouwers** [comment]
As mentioned this package isn't actively maintained or supported anymore. I just merged a PR that ads L10 support.

**Comment by Levivb** [comment]
thanks nonetheless :D
