### ISSUE TITLE
Laravel 5.1: Sortable trait problem with order method ? 

### ISSUE THREAD

**Issue by sdebacker** [Maatwebsite/Laravel-Sidebar#9]
Since laravel 5.1, my groups and items are no more sorted by weight, am I alone with this issue ?

**Comment by patrickbrouwers** [comment]
Using it in 5.1 as well, but didn't note any difference yet.

Didn't something change in the Laravel Collections? Can't remember if it had anything to do with sorting. Will have a look at it soon

**Comment by sdebacker** [comment]
I SidebarManager class, I had to replace 

``` php
$this->order(
    $this->groups,
    'weight'
);
```

by

``` php
$this->groups = $this->groups->sortBy('weight');
```

in order to have groups ordered. I need to apply the same change for items in groups.

**Comment by nWidart** [comment]
Pull request time! :smiley:

**Comment by nWidart** [comment]
No PSR-2!?! :P

**Comment by patrickbrouwers** [comment]
Is merged as well ;) Don't you worry :D
